export const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  textAlign: "center",
  transform: "translate(-50%, -50%)",
  width: 400,
  background: "rgba(23, 23, 24, 0.56)",
  border: "1px solid rgba(23, 23, 24, 1)",
  boxShadow: 24,
  borderRadius: "16px",
  backdropFilter: "blur(8.6px)",
  webkitBackdropFilter: "blur(8.6px)",
  p: 4,
  color: "white",
};

export const buttonStyle = {
  display: "flex",
  padding: "1.5em 2em",
  border: "1.5px solid #1aabcd",
  color: "#1aabcd",
  textTransform: "none",
  marginLeft: "10px",
  fontFamily: "Poppins, Arial, Helvetica, sans-serif",
  fontStyle: "normal",
  fontWeight: "500",
  fontSize: "11px",
  lineHeight: "10px",
  borderRadius: "8px",
  cursor: "pointer",
  backgroundColor: "transparent",
  transition: "all 0.5s",
};

export const buttonPopUpStyle = {
  display: "flex",
  padding: "1.5em 2em",
  border: "none",
  color: "#ffff",
  textTransform: "none",
  fontFamily: "Poppins, Arial, Helvetica, sans-serif",
  fontStyle: "normal",
  fontWeight: "500",
  fontSize: "12px",
  lineHeight: "10px",
  borderRadius: "8px",
  cursor: "pointer",
  backgroundColor: "#1aabcd",
  transition: "all 0.5s",
  marginLeft: "138px",
  marginTop: "20px",
  marginBottom: "20px",
};
